### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by borpin** [emoncms/app#47]
I suspect this is thrown because there are no suitable feeds. Perhaps this should be handled a little better.

```
Fatal error: Uncaught Error: Call to a member function fetch_object() on boolean in /var/www/emoncms/Modules/app/AppConfig_model.php:167 Stack trace: 
#0 /var/www/emoncms/Modules/app/AppConfig_model.php(34): AppConfig->get(1) 
#1 /var/www/emoncms/Modules/app/app_controller.php(94): AppConfig->applist(1) 
#2 /var/www/emoncms/core.php(64): app_controller() 
#3 /var/www/emoncms/index.php(189): controller('app') 
#4 {main} thrown in /var/www/emoncms/Modules/app/AppConfig_model.php on line 167
```

**Comment by borpin** [comment]
My point was that any error in the database should be handled in a more friendly way :smile:
